name: Publish to npm

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  npm-publish:
    runs-on: ubuntu-22.04
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - name: Fetch npm packages
        uses: actions/download-artifact@v8
        with:
          pattern: artifacts-*
          path: npm/
          merge-multiple: true
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - name: Install a trusted-publishing-compatible npm CLI
        run: npm install --global npm@^11.5.1
      - name: Publish npm packages with OIDC
        run: |
          for release in $(echo "$PLAN" | jq --compact-output '.releases[] | select([.artifacts[] | endswith("-npm-package.tar.gz")] | any)'); do
            pkg=$(echo "$release" | jq '.artifacts[] | select(endswith("-npm-package.tar.gz"))' --raw-output)
            npm publish --access public "./npm/${pkg}"
          done
